[default_session]
startup_command = "nvim -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "chezmoi edit --apply ~/.config/tmux/tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "scopinator"
path = "~/Projects/erewhon/scopinator/"
# startup_command = "pwd"
# windows = [ "claude" ]

[[window]]
name = "shell"

[[window]]
name = "claude"
startup_script = "claude"
