add_newline = false
format = """$directory$character"""
palette = "catppuccin_mocha"
right_format = """$all"""
command_timeout = 1000

[cmd_duration]
min_time = 0
show_milliseconds = true
format = ' [$duration]($style)'

[directory]
truncation_length = 8
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
untracked = '  ?${count}'
stashed = ' ${count}'
modified = ' ~${count}'
staged = '[++\($count\)](green)'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
format = '\[[$ahead_behind $all_status]($style)\] '

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = true
style = 'bold blue'
symbol = " "

[golang]
format = '[ ](bold cyan)'

[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:577926974532:cluster/zd-pvc-omer", style = "green", context_alias = "omerxx", symbol = " " },
]

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[docker_context]
disabled = true

[terraform]
format = '[$symbol$workspace]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
